package flightscheduleradithyankurupaqk5645;


import flightscheduleradithyankurupaqk5645.Flight;
import java.awt.event.ActionEvent;
import java.beans.Visibility;
import java.sql.Date;
import java.text.*;
import java.util.logging.*;
import javafx.beans.value.*;
import javax.swing.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author adith
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        refresh();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        tabbedPane = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        addJLabel1 = new javax.swing.JLabel();
        addTextField1 = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        customerRadioButton = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        flightRadioButton = new javax.swing.JRadioButton();
        dayRadioButton = new javax.swing.JRadioButton();
        addJLabel2 = new javax.swing.JLabel();
        addTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bookingFlightCombo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        bookingDateCombo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        bookingButton = new javax.swing.JButton();
        bookingCustomerCombo = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        statusFlightRadioButton = new javax.swing.JRadioButton();
        statusWaitlistRadioButton = new javax.swing.JRadioButton();
        statusJLabel1 = new javax.swing.JLabel();
        statusComboBox2 = new javax.swing.JComboBox<>();
        statusJLabel2 = new javax.swing.JLabel();
        statusComboBox1 = new javax.swing.JComboBox<>();
        statusButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        statusCustomerRadioButton = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        cancelCustomerCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cancelDayCombo = new javax.swing.JComboBox<>();
        cancelButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        dropFlightCombo = new javax.swing.JComboBox<>();
        dropButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setText("Flight Scheduler");

        addJLabel1.setText("Blank");

        addTextField1.setColumns(10);
        addTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTextField1ActionPerformed(evt);
            }
        });

        addButton.setAction(new AbstractAction() {     
            @Override
            public void actionPerformed(ActionEvent e) {
                Customer.addCustomer(addTextField1.getText());
                //bookingCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(Customer.getCustomer().toArray(new String[Customer.getCustomer().size()])));
                //buttonGroup1.clearSelection();
                refresh();
            }
        });
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(customerRadioButton);
        customerRadioButton.setText("Customer");
        customerRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerRadioButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("Add");

        buttonGroup2.add(flightRadioButton);
        flightRadioButton.setText("Flight");
        flightRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(dayRadioButton);
        dayRadioButton.setText("Day");
        dayRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayRadioButtonActionPerformed(evt);
            }
        });

        addJLabel2.setText("Blank");

        addTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerRadioButton)
                    .addComponent(jLabel10)
                    .addComponent(flightRadioButton)
                    .addComponent(dayRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addJLabel2)
                    .addComponent(addJLabel1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(87, 87, 87))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addJLabel1)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerRadioButton))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(flightRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dayRadioButton))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(addJLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Add", jPanel4);

        jLabel1.setText("Select a Flight");

        bookingFlightCombo.setModel(new javax.swing.DefaultComboBoxModel<>(Flight.getFlights().toArray(new String[Flight.getFlights().size()])));
        bookingFlightCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingFlightComboActionPerformed(evt);
            }
        });

        jLabel6.setText("Select a Day");

        bookingDateCombo.setModel(new javax.swing.DefaultComboBoxModel<>(Day.getDays().toArray(new String[Day.getDays().size()])));
        bookingDateCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingDateComboActionPerformed(evt);
            }
        });

        jLabel7.setText("Customer Name");

        bookingButton.setAction(new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String flight = bookingFlightCombo.getSelectedItem().toString();
                String date = bookingDateCombo.getSelectedItem().toString();
                String customer = bookingCustomerCombo.getSelectedItem().toString();
            }
        });
        bookingButton.setText("Book");
        bookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingButtonActionPerformed(evt);
            }
        });

        bookingCustomerCombo.setModel(new javax.swing.DefaultComboBoxModel<>(Customer.getCustomer().toArray(new String[Customer.getCustomer().size()])));
        bookingCustomerCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingCustomerComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bookingFlightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bookingDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookingCustomerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 307, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(bookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingFlightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingCustomerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(bookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        tabbedPane.addTab("Book", jPanel1);

        jLabel3.setText("View Status");

        buttonGroup1.add(statusFlightRadioButton);
        statusFlightRadioButton.setText("Flight");
        statusFlightRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusFlightRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(statusWaitlistRadioButton);
        statusWaitlistRadioButton.setText("Waitlist");

        statusJLabel1.setText("Day");

        statusJLabel2.setText("Blank");

        statusComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusComboBox1ActionPerformed(evt);
            }
        });

        statusButton.setAction(new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                statusButtonActionPerformed(e);

            }
        });
        statusButton.setText("Check Status");
        statusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButtonActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        buttonGroup1.add(statusCustomerRadioButton);
        statusCustomerRadioButton.setText("Customer");
        statusCustomerRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusCustomerRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(statusWaitlistRadioButton)
                                    .addComponent(statusFlightRadioButton)
                                    .addComponent(statusCustomerRadioButton))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusJLabel2)
                            .addComponent(statusComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusJLabel1))
                        .addGap(114, 114, 114))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(statusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(statusJLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statusFlightRadioButton)
                            .addComponent(statusComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusWaitlistRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusCustomerRadioButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(statusJLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        statusWaitlistRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusWaitlistRadioButtonActionPerformed(evt);
            }
        });

        tabbedPane.addTab("Status", jPanel3);

        cancelCustomerCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelCustomerComboActionPerformed(evt);
            }
        });

        jLabel5.setText("Customer");

        jLabel8.setText("Day");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cancelDayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cancelCustomerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelCustomerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelDayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Cancel", jPanel2);

        jLabel4.setText("Flight Name");

        dropFlightCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropFlightComboActionPerformed(evt);
            }
        });

        dropButton.setText("Drop");
        dropButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(dropFlightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(dropButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dropFlightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(dropButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Drop", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabbedPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookingDateComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingDateComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingDateComboActionPerformed

    private void bookingCustomerComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingCustomerComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingCustomerComboActionPerformed

    private void bookingFlightComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingFlightComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingFlightComboActionPerformed

    private void bookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingButtonActionPerformed
        String flight = bookingFlightCombo.getSelectedItem().toString();
        String date = bookingDateCombo.getSelectedItem().toString();
        String customer = bookingCustomerCombo.getSelectedItem().toString();
        Booking.addBooking(flight, date, customer);
        javax.swing.JOptionPane.showMessageDialog(this, "Booking made for " + customer + " on flight " + flight + " on " + date + ".");
            
    }//GEN-LAST:event_bookingButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if (add == 1){
            Customer.addCustomer(addTextField1.getText());
            javax.swing.JOptionPane.showMessageDialog(this, "New customer added: " + addTextField1.getText());
        }
        else if (add == 2){
            Flight.addFlight(addTextField1.getText(), Integer.parseInt(addTextField2.getText()));
            javax.swing.JOptionPane.showMessageDialog(this, "New flight added: " + addTextField1.getText() + " with " + addTextField2.getText() + " seats.");
        }
        else if (add == 3){
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            try {
                Day.addDay(new java.sql.Date(sdf.parse(addTextField1.getText()).getTime()));
                javax.swing.JOptionPane.showMessageDialog(this, "New day added: " + addTextField1.getText());
            }
            catch(Exception e){
                javax.swing.JOptionPane.showMessageDialog(this, "Please use the YYYY-MM-DD date format");
            }
        }
        else {
            javax.swing.JOptionPane.showMessageDialog(this, "Please specify what to add.");
        }
        refresh();
    }//GEN-LAST:event_addButtonActionPerformed

    private void addTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTextField1ActionPerformed

    private void statusFlightRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusFlightRadioButtonActionPerformed
        status = 1;
        statusJLabel1.setVisible(true);
        statusComboBox1.setVisible(true);
        statusJLabel2.setVisible(true);
        statusComboBox2.setVisible(true);
        statusJLabel1.setText("Date");
        statusComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(Day.getDays().toArray(new String[Day.getDays().size()])));
        statusJLabel2.setText("Flight");
        statusComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(Flight.getFlights().toArray(new String[Flight.getFlights().size()])));

    }//GEN-LAST:event_statusFlightRadioButtonActionPerformed

    private void dayRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayRadioButtonActionPerformed
        add = 3;
        addJLabel1.setVisible(true);
        addTextField1.setVisible(true);
        addJLabel2.setVisible(false);
        addTextField2.setVisible(false);
        addJLabel1.setText("Day (YYYY-MM-DD)");
    }//GEN-LAST:event_dayRadioButtonActionPerformed

    private void statusComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusComboBox1ActionPerformed

    private void customerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerRadioButtonActionPerformed
        add = 1;
        addJLabel1.setVisible(true);
        addTextField1.setVisible(true);
        addJLabel2.setVisible(false);
        addTextField2.setVisible(false);
        addJLabel1.setText("Customer Name");
    }//GEN-LAST:event_customerRadioButtonActionPerformed

    private void flightRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightRadioButtonActionPerformed
        add = 2;
        addJLabel1.setVisible(true);
        addTextField1.setVisible(true);
        addJLabel2.setVisible(true);
        addTextField2.setVisible(true);
        addJLabel1.setText("Flight Name");
        addJLabel2.setText("Number of Seats");
    }//GEN-LAST:event_flightRadioButtonActionPerformed

    private void statusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButtonActionPerformed
                // TODO add your handling code here:
        String statusResult="";
        if (status == 1){
            statusResult = "Date: " + statusComboBox1.getSelectedItem().toString()+"\nFlight: " + statusComboBox2.getSelectedItem().toString()+"\n";
            statusResult += Status.statusFlight(statusComboBox1.getSelectedItem().toString(),statusComboBox2.getSelectedItem().toString());
        }
        else if (status == 2){
            statusResult = "Waitlist for " + statusComboBox1.getSelectedItem().toString() + "\n";
            statusResult += Status.statusWaitlist(statusComboBox1.getSelectedItem().toString());
        }
        else if (status == 3){
            statusResult ="Customer: "+statusComboBox1.getSelectedItem().toString()+"\n";
            statusResult += Status.statusCustomer(statusComboBox1.getSelectedItem().toString());
        }
        else {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a status.");
        }
        jTextArea1.setText(statusResult);
    }//GEN-LAST:event_statusButtonActionPerformed

    private void statusCustomerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusCustomerRadioButtonActionPerformed
        // TODO add your handling code here:
        status = 3;
        statusJLabel1.setVisible(true);
        statusComboBox1.setVisible(true);
        statusJLabel2.setVisible(false);
        statusComboBox2.setVisible(false);
        statusJLabel1.setText("Customer");
        statusComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(Customer.getCustomer().toArray(new String[Customer.getCustomer().size()])));
    }//GEN-LAST:event_statusCustomerRadioButtonActionPerformed

    private void dropFlightComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropFlightComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropFlightComboActionPerformed

    private void addTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTextField2ActionPerformed

    private void dropButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropButtonActionPerformed
        // TODO add your handling code here:
        String flight = dropFlightCombo.getSelectedItem().toString();
        Flight.dropFlight(flight);
        javax.swing.JOptionPane.showMessageDialog(this, "Flight " + flight + " has been dropped.\n" + "Changes in bookings has been made.");
        refresh();
    }//GEN-LAST:event_dropButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
            String customer = cancelCustomerCombo.getSelectedItem().toString();
            String day = cancelDayCombo.getSelectedItem().toString();
            Booking.cancelBooking(customer, day);
        javax.swing.JOptionPane.showMessageDialog(this, "Booking cancelled for " + customer + " on " + day + ".");
        refresh();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void cancelCustomerComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelCustomerComboActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cancelCustomerComboActionPerformed
    private void statusWaitlistRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                          
        // TODO add your handling code here:
        status = 2;
        statusJLabel1.setVisible(true);
        statusComboBox1.setVisible(true);        
        statusJLabel2.setVisible(false);
        statusComboBox2.setVisible(false);
        statusJLabel1.setText("Date");
        statusComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(Day.getDays().toArray(new String[Day.getDays().size()])));
    }
    
    private void refresh(){
        add = 0;
        status = 0;
        bookingCustomerCombo.setModel(new javax.swing.DefaultComboBoxModel<>(Customer.getCustomer().toArray(new String[Customer.getCustomer().size()])));
        bookingFlightCombo.setModel(new javax.swing.DefaultComboBoxModel<>(Flight.getFlights().toArray(new String[Flight.getFlights().size()])));
        bookingDateCombo.setModel(new javax.swing.DefaultComboBoxModel<>(Day.getDays().toArray(new String[Day.getDays().size()])));
        dropFlightCombo.setModel(new javax.swing.DefaultComboBoxModel<>(Flight.getFlights().toArray(new String[Flight.getFlights().size()])));
        cancelCustomerCombo.setModel(new javax.swing.DefaultComboBoxModel<>(Customer.getCustomer().toArray(new String[Customer.getCustomer().size()])));
        cancelDayCombo.setModel(new javax.swing.DefaultComboBoxModel<>(Day.getDays().toArray(new String[Day.getDays().size()])));
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        statusJLabel1.setVisible(false);
        statusJLabel2.setVisible(false);
        statusComboBox1.setVisible(false);
        statusComboBox2.setVisible(false);
        addTextField1.setText("");
        addTextField2.setText("");
        addJLabel1.setVisible(false);
        addTextField1.setVisible(false);
        addJLabel2.setVisible(false);
        addTextField2.setVisible(false);
        jTextArea1.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException e) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, e);
        } catch (InstantiationException e) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, e);
        } catch (IllegalAccessException e) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, e);
        } catch (javax.swing.UnsupportedLookAndFeelException e) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, e);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    public static int status = 0;
    public static int add = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addJLabel1;
    private javax.swing.JLabel addJLabel2;
    public javax.swing.JTextField addTextField1;
    private javax.swing.JTextField addTextField2;
    private javax.swing.JButton bookingButton;
    private javax.swing.JComboBox<String> bookingCustomerCombo;
    private javax.swing.JComboBox<String> bookingDateCombo;
    private javax.swing.JComboBox<String> bookingFlightCombo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> cancelCustomerCombo;
    private javax.swing.JComboBox<String> cancelDayCombo;
    private javax.swing.JRadioButton customerRadioButton;
    private javax.swing.JRadioButton dayRadioButton;
    private javax.swing.JButton dropButton;
    private javax.swing.JComboBox<String> dropFlightCombo;
    private javax.swing.JRadioButton flightRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton statusButton;
    private javax.swing.JComboBox<String> statusComboBox1;
    private javax.swing.JComboBox<String> statusComboBox2;
    private javax.swing.JRadioButton statusCustomerRadioButton;
    private javax.swing.JRadioButton statusFlightRadioButton;
    private javax.swing.JLabel statusJLabel1;
    private javax.swing.JLabel statusJLabel2;
    private javax.swing.JRadioButton statusWaitlistRadioButton;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
